---

# Login credentials
ansible_user: ansible
ansible_ssh_private_key_file: "{{ lookup('env', 'PWD') }}/ssh/ansible.pem"

ansible_python_interpreter: /usr/bin/python3

gocd_server_ip: 144.202.51.184
