---

  - name: update CloudFlare DNS records
    cloudflare_dns:
      zone: "{{ cloudflare_zone }}"
      record: "{{ cloudflare_subdomain }}"
      type: A
      value: "{{ ansible_default_ipv4.address }}"
      account_email: "{{ cloudflare_username }}"
      account_api_token: "{{ cloudflare_password_token }}"

